from .admin import router as admin_router
from .command import router as command_router
from .database import router as database_router
from .file import router as file_router
from .login import router as login_router
from .metircs import router as metrics_router
from .user import router as user_router
from .timeline import router as time_router
from .bubble import router as bubble_router
from .panel import router as panel_router
from .log import router as log_router
from .wiki import router as wiki_router
